services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=pharmaFind'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=pharmaFind'
      - 'PGDATA=/var/lib/postgresql/data'
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pharmaFind
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: pharmaFind
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
        - pharmaFind

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
        - pharmaFind

  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:25.0.1
    command: start-dev
    networks:
      - pharmaFind

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - pharmaFind
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - pharmaFind
    volumes:
      - minio:/minio/data
    restart: unless-stopped


networks:
  pharmaFind:
    driver: bridge

volumes:
    mongo-data:
      driver: local
    minio:
      driver: local