spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    config:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
      serviceUrl:
          defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}