spring:
  data:
    mongodb:
      username: root
      password: root
      database: pharmaFind
      host: localhost
      port: 27017
      authentication-database: admin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
server:
  port: 8083